# stolen from https://github.com/ublue-os/toolboxes/blob/main/toolboxes/fedora-toolbox/Containerfile.fedora
FROM registry.fedoraproject.org/fedora-toolbox:42 AS fedora-toolbox

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience powered by Fedora" 

COPY ./toolbox/packages.fedora /tmp/toolbox-packages

RUN dnf -y upgrade && \
    dnf -y install $(</tmp/toolbox-packages) && \
    dnf clean all

# Install RPMFusion for hardware accelerated encoding/decoding
RUN dnf install -y \
    "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm" && \
    dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld && \
    dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld && \
    dnf clean all

RUN dnf copr enable atim/lazygit -y && \
    dnf install -y lazygit && \
    dnf clean all

RUN npm install -g @anthropic-ai/claude-code

# Cleanup
RUN rm -rf /tmp/*

RUN mkdir -p /usr/local/bin  && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \ 
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker
