FROM quay.io/fedora-ostree-desktops/sway-atomic:43

COPY desktop/shared/etc /etc
COPY desktop/shared/usr /usr
COPY desktop/niri/etc /etc
COPY desktop/shared/scripts/*.sh /usr/local/bin/
COPY desktop/niri/scripts/*.sh /usr/local/bin/

RUN bash /usr/local/bin/cleanup.sh && \
    ostree container commit && \
    bash /usr/local/bin/install.sh && \
    ostree container commit && \
    bash /usr/local/bin/systemd.sh && \
    bash /usr/local/bin/firewalld.sh && \
    rm /usr/local/bin/*.sh && \
    ostree container commit

RUN bootc container lint

LABEL containers.bootc="1" \
      ostree.bootable="1"
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
