FROM quay.io/fedora-ostree-desktops/sway-atomic:42

COPY desktop/sway/etc /etc
COPY desktop/sway/usr /usr
COPY desktop/sway/scripts/*.sh  /usr/local/bin/

RUN bash /usr/local/bin/install.sh && \
    ostree container commit

RUN bash /usr/local/bin/systemd.sh && \
    ostree container commit

RUN bash /usr/local/bin/firewalld.sh && \
    ostree container commit

RUN bootc container lint

LABEL containers.bootc="1" \
      ostree.bootable="1"
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
