#!/usr/bin/env bash
set -euo pipefail

groupadd plugdev

readarray -t wheelarray < <(getent group wheel | cut -d ":" -f 4 | tr ',' '\n')
for user in "${wheelarray[@]}"; do
  usermod -aG plugdev "$user"
done
