FROM quay.io/fedora/fedora-bootc:41

# dnf configuration has to be in effect during build
COPY edge/etc/dnf /etc/dnf

# Bulk of layered packages
RUN dnf5 -y install \
      vim \
      tmux \
      bat \
      btop \
      pv \
      zstd \
      nmap-ncat \
      firewalld \
      tailscale \
      fail2ban \
      fail2ban-firewalld \
      fail2ban-selinux


# Set vim as default editor
RUN dnf5 -y swap nano-default-editor vim-default-editor

# Remove unneeded packages (currently doesn't actually reduce space, but reduces clutter)
RUN dnf5 -y autoremove

COPY edge/etc /etc

# RUN firewall-offline-cmd --set-default-zone public
RUN firewall-offline-cmd --add-service https
RUN firewall-offline-cmd --remove-service mdns

RUN firewall-offline-cmd --new-policy container-redirect && \
    firewall-offline-cmd --policy container-redirect --add-forward-port=port=80:proto=tcp:toport=8000 && \
    firewall-offline-cmd --zone public --add-policy container-redirect && \
    firewall-offline-cmd --save


RUN systemctl enable tailscaled.service
RUN systemctl enable firewalld
RUN systemctl enable fail2ban

# composefs has / as RO. this service fails. todo: check why
RUN systemctl mask systemd-remount-fs.service

# Restrict permissions on quadlet directory
RUN chmod 700 /etc/containers/systemd

# https://github.com/ostreedev/ostree-rs-ext/issues/159
RUN ostree container commit
