#!/usr/bin/env bash
set -euo pipefail

groupadd -f plugdev

readarray -t wheelarray < <(getent group wheel | cut -d ":" -f 4 | tr ',' '\n')
for user in "${wheelarray[@]}"; do
  [[ -n "$user" ]] && usermod -aG plugdev "$user" || true
done
